image: "paritytech/ci-linux:production"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build:
  stage: build
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
  
lint:
  stage: test
  script:
    - cargo +nightly --version
    - cargo +nightly fmt --all -- --check
    - cargo +nightly clippy

