# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Rust.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build-job:
  stage: build
  before_script:
  - apt-get update
  - apt install -y git clang curl libssl-dev llvm libudev-dev
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  - source ~/.cargo/env
  - rustup default stable
  - rustup update
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  - cargo +nightly install clippy
  script:
    - cargo build --workspace --all-features
  cache:
    paths:
      - target/
      - cargo/

test:
  stage: test
  script:
    - cargo test --workspace --all-features
  cache:
    paths:
      - target/
      - cargo/
  
lint:
  stage: test
  script:
    - cargo +nightly clippy --workspace --all-features
  cache:
    paths:
      - target/
      - cargo/
