image: "paritytech/ci-linux:production"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - target/
  policy: pull-push

build:
  stage: build
  script:
    - rustup show
    - cargo build

test:
  stage: test
  script:
    - cargo test
  
lint:
  stage: test
  script:
    - cargo +nightly fmt --all -- --check
    - cargo +nightly clippy

