image: "paritytech/ci-linux:production"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

build:
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - cargo test
  dependencies:
    - build
  
lint:
  stage: test
  script:
    - cargo +nightly fmt --all -- --check
    - cargo +nightly clippy
  dependencies:
    - build

