image: "rust:latest"

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

cache:
  paths:
    - target/
    - cargo/

build-job:
  stage: build
  before_script:
  - apt-get update
  - apt install -y git clang curl libssl-dev llvm libudev-dev
  - rustup default stable
  - rustup update
  - rustup update nightly
  - rustup target add wasm32-unknown-unknown --toolchain nightly
  script:
    - cargo build

test:
  stage: test
  script:
    - cargo test
  
lint:
  stage: test
  before_script:
  - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo clippy

